  import './globals.css'
  // components
  import Navbar from './components/Navbar'
  import ParticleBackground from './components/background_comp'

  export const metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
  }

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className='main-div text-cyberpunk-pink bg-cyberpunk-bg border-cyberpunk-border p-5 mx-auto my-auto'>
        <Navbar/>
        {children}
        </body>
      </html>
    )
  }