  import './globals.css'
  // components
  import Navbar from './components/Navbar'
  import ParticleBackground from './components/background_comp'

  export const metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
  }

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
        <Navbar/>
        {children}

        </body>
      </html>
    )
  }